spring:
#  ???thymleaf??
  thymeleaf:
    cache: false
#    ????????????hikari ??   springb??????
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
#      ????????????? 10??????????
      idle-timeout: 180000
#      ????? ????10
      maximum-pool-size: 10
#      ?????????????
      auto-commit: true
#      ??????????????????????  0-??????
      max-lifetime: 180000
#      ??????  ????30s
      connection-timeout: 30000
#      ?????????sql??
      connection-test-query: SELECT 1

mybatis-plus:
#  mapper.xml?????
  mapper-locations: classpath*:/mapper/*Mapper.xml
#  ??mybatis????????
  type-aliases-package: com.fanxuekang.seckill.pojo


# mybatis sql????
logging:
  level:
    com.fanxuekang.seckill.mapper: debug
