spring:

#  ???thymleaf??
  thymeleaf:
    cache: false
#    数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
#      ????????????? 10??????????
      idle-timeout: 180000
#      ????? ????10
      maximum-pool-size: 10
#      ?????????????
      auto-commit: true
#      ??????????????????????  0-??????
      max-lifetime: 180000
#      ??????  ????30s
      connection-timeout: 30000
#      ?????????sql??
      connection-test-query: SELECT 1

  redis:
#    主机，端口号
    host: 192.168.40.128
    port: 6379
#    数据库
    database: 0
#    连接超时时间
    shutdown-timeout: 10000ms

    lettuce:
      pool:
#        最大连接数
        max-active: 8
#        最大连接阻塞等待时间
        max-wait: 10000ms
#        最大的空闲连接
        max-idle: 200
#        最小空闲连接
        min-idle: 5


mybatis-plus:
#  mapper.xml?????
  mapper-locations: classpath*:/mapper/*Mapper.xml
#  ??mybatis????????
  type-aliases-package: com.fanxuekang.seckill.pojo


# mybatis sql????
logging:
  level:
    com.fanxuekang.seckill.mapper: debug
